from os import environ
URL_WHISPER_SERVICE_ENDPOINT=environ.get('URL_WHISPER_SERVICE_ENDPOINT')
URL_TEXTANALYZER_ENDPOINT=environ.get('URL_TEXTANALYZER_ENDPOINT')
URL_LISTRESULTS_ENDPOINT=environ.get('URL_LISTRESULTS_ENDPOINT')
URL_SINGLERESULT_ENDPOINT=environ.get('URL_SINGLERESULT_ENDPOINT')